# Generated by Django 3.2.20 on 2023-07-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='expiry',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('VISA', 'Visa'), ('RUPY', 'RuPay'), ('MSTR', 'Master Card')], default='VISA', max_length=4),
        ),
    ]
