# Generated by Django 3.2.20 on 2023-07-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20230716_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=16, unique=True, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=3, null=True, verbose_name='CVV'),
        ),
    ]
