# Generated by Django 4.2.23 on 2025-08-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_is_paid_card_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='billed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Billed At'),
        ),
        migrations.AddField(
            model_name='card',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Credit Limit'),
        ),
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='card',
            name='last_bill_amount',
            field=models.IntegerField(default=0, verbose_name='Last Bill Amount'),
        ),
        migrations.AddField(
            model_name='card',
            name='reward_points',
            field=models.IntegerField(default=0, verbose_name='Reward Points'),
        ),
    ]
