name: Docker

on:
  push:
    branches:
      - master

jobs:
  push-job:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
          
      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1.0.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: "${{secrets.PROD_SERVER_IP}}"
          app-name: "cardman"
          git-push-flags: "--force"